version: '3.8' # Por tener docker v19.03.0 o superior

services:
    database:
        image: mariadb:latest
        container_name: mariadb_gdp
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: gestion_de_practica
            MYSQL_USER: admin
            MYSQL_PASSWORD: 1234
        volumes:
            - ./database/init/:/docker-entrypoint-initdb.d/
        command: 
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        ports:  
            - 3308:3306